# Generated by Django 5.2.7 on 2025-10-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='message',
            name='role',
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(default='New Chat', max_length=255),
        ),
    ]
